-- ADMIN_MODULE
INSERT INTO ADMIN_MODULE (MODULE_ID, MODULE_NAME, MODULE_CODE, MODULE_URL, PARENT_ID, IS_ENABLE, IS_SHOW) VALUES ('1', '项目', 'MODULE_PROJECT', '', '0', '1', '1');
INSERT INTO ADMIN_MODULE (MODULE_ID, MODULE_NAME, MODULE_CODE, MODULE_URL, PARENT_ID, IS_ENABLE, IS_SHOW) VALUES ('2', '乐米彩票', 'MODULE_LEMI_DEV', '/LEMI/DEV', '1', '1', '1');
INSERT INTO ADMIN_MODULE (MODULE_ID, MODULE_NAME, MODULE_CODE, MODULE_URL, PARENT_ID, IS_ENABLE, IS_SHOW) VALUES ('3', '乐米彩票MST环境', 'MODULE_LEMI_MST', '/LEMI/MST', '1', '1', '1');
INSERT INTO ADMIN_MODULE (MODULE_ID, MODULE_NAME, MODULE_CODE, MODULE_URL, PARENT_ID, IS_ENABLE, IS_SHOW) VALUES ('4', '乐仑炫彩', 'MODULE_LELUN_DEV', '/LELUN/DEV', '1', '1', '1');
INSERT INTO ADMIN_MODULE (MODULE_ID, MODULE_NAME, MODULE_CODE, MODULE_URL, PARENT_ID, IS_ENABLE, IS_SHOW) VALUES ('5', '乐仑炫彩MST环境', 'MODULE_LELUN_MST', '/LELUN/MST', '1', '1', '0');
INSERT INTO ADMIN_MODULE (MODULE_ID, MODULE_NAME, MODULE_CODE, MODULE_URL, PARENT_ID, IS_ENABLE, IS_SHOW) VALUES ('6', '资源', 'MODULE_ASSET', '/asset', '0', '1', '1');
INSERT INTO ADMIN_MODULE (MODULE_ID, MODULE_NAME, MODULE_CODE, MODULE_URL, PARENT_ID, IS_ENABLE, IS_SHOW) VALUES ('7', 'MODULE_NAME_7', 'MODULE_CODE_7', 'MODULE_URL_7', '0', '1', '1');
INSERT INTO ADMIN_MODULE (MODULE_ID, MODULE_NAME, MODULE_CODE, MODULE_URL, PARENT_ID, IS_ENABLE, IS_SHOW) VALUES ('8', 'MODULE_NAME_8', 'MODULE_CODE_8', 'MODULE_URL_8', '0', '1', '1');
INSERT INTO ADMIN_MODULE (MODULE_ID, MODULE_NAME, MODULE_CODE, MODULE_URL, PARENT_ID, IS_ENABLE, IS_SHOW) VALUES ('9', 'MODULE_NAME_9', 'MODULE_CODE_9', 'MODULE_URL_9', '0', '1', '1');
INSERT INTO ADMIN_MODULE (MODULE_ID, MODULE_NAME, MODULE_CODE, MODULE_URL, PARENT_ID, IS_ENABLE, IS_SHOW) VALUES ('10', 'MODULE_NAME_10', 'MODULE_CODE_10', 'MODULE_URL_10', '0', '1', '1');


-- ADMIN_RESOURCE


